//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLAManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignaturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asignaturas()
        {
            this.DetalleProfesorAsignatura = new HashSet<DetalleProfesorAsignatura>();
            this.EstudianteSeleccionAsignatura = new HashSet<EstudianteSeleccionAsignatura>();
        }
    
        public int IDAsignatura { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleProfesorAsignatura> DetalleProfesorAsignatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstudianteSeleccionAsignatura> EstudianteSeleccionAsignatura { get; set; }
    }
}
