//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITLAManage.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ManageITLAContext : DbContext
    {
        public ManageITLAContext()
            : base("name=ManageITLAContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asignaturas> Asignaturas { get; set; }
        public virtual DbSet<DetalleProfesorAsignatura> DetalleProfesorAsignatura { get; set; }
        public virtual DbSet<Estudiantes> Estudiantes { get; set; }
        public virtual DbSet<EstudianteSeleccionAsignatura> EstudianteSeleccionAsignatura { get; set; }
        public virtual DbSet<Profesores> Profesores { get; set; }
    
        public virtual int sp_borrarAsignatura(Nullable<int> iDAsignatura)
        {
            var iDAsignaturaParameter = iDAsignatura.HasValue ?
                new ObjectParameter("IDAsignatura", iDAsignatura) :
                new ObjectParameter("IDAsignatura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_borrarAsignatura", iDAsignaturaParameter);
        }
    
        public virtual int sp_borrarProfesor(Nullable<int> iDProf)
        {
            var iDProfParameter = iDProf.HasValue ?
                new ObjectParameter("IDProf", iDProf) :
                new ObjectParameter("IDProf", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_borrarProfesor", iDProfParameter);
        }
    
        public virtual int sp_borrarEstudiante(Nullable<int> iDEst)
        {
            var iDEstParameter = iDEst.HasValue ?
                new ObjectParameter("IDEst", iDEst) :
                new ObjectParameter("IDEst", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_borrarEstudiante", iDEstParameter);
        }
    }
}
